[build]
command = "npm run build"
publish = "dist"
functions = "dist/netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@libsql/client"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200